name: Ci/CD Pipeline to AWS ElasticBeanstalk
env:
    EB_PACKAGE_S3_BUCKET_NAME: "elasticbeanstalk-eu-central-1-431384745395"
    EB_APPLICATION_NAME: "GitActions-Eriks-env2"
    EB_ENVIRONMENT_NAME: "GitActions-Eriks-env2"
    DEPLOY_PACKAGE_NAME: "php_Eriks_${{ github.sha }}.zip"
    AWS_REGION_NAME: "eu-central-1"

on:
    push:
        branches: 
            - main

jobs:
    ci-part:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Create ZIP package
              run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
                aws-region            : ${{ env.AWS_REGION_NAME }}

            - name: Copy Deployment package to S3 bucket
              run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

            - name: Print Message for CI finish
              run: echo "CI Pipeline successfully done"

    cd-part:
        runs-on: ubuntu-latest
        needs: ci-part
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
                aws-region            : ${{ env.AWS_REGION_NAME }}
            
            - name: Create new application
              run: |
                aws elasticbeanstalk create-application-version \
                --application-name ${{ env.EB_APPLICATION_NAME }} \
                --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
                --version-label "Version-${{ github.sha }}" \
                --description "CommitSHA-${{ github.sha }}"

            - name: Deploy new application
              run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Version-${{ github.sha }}"

            - name: Print message
              run: echo "CD Pipeline successfully done"
